version: "3.0"

services:
  memcached:
    image: memcached
    container_name: memcached
    restart: always
    expose:
      - "11211"
    network_mode: bridge

  yopass:
    image: yopass:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "1337"
    restart: always
    command: ["--database=memcached", "--memcached=memcached:11211"]
    environment:
      - VIRTUAL_HOST=secret.salaourn.com
      - LETSENCRYPT_HOST=secret.salaourn.com
      - LETSENCRYPT_EMAIL=dprisc97@gmail.com
    network_mode: bridge
    links:
      - memcached
