version: "3.0"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"
    network_mode: bridge

  yopass:
    image: yopass:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    command: "--memcached=memcached:11211 --port 8080"
    environment:
      - VIRTUAL_HOST=secret.salaourn.com
      - LETSENCRYPT_HOST=secret.salaourn.com
      - LETSENCRYPT_EMAIL=dprisc97@gmail.com
    network_mode: bridge
