name: Deploy [MAIN]

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Deploy Salaourn Secret Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            REPO_DIR="$(basename ${{ github.repository }})"
            if [ -d "$REPO_DIR" ]; then
              cd "$REPO_DIR"
              git pull origin master
            else
              git clone https://$GH_TOKEN@github.com/${{ github.repository }}.git
              cd "$REPO_DIR"
            fi
            docker-compose -f docker-compose-prod.yml build --no-cache
            docker-compose -f docker-compose-prod.yml up -d --force-recreate
